import type { CSSProperties } from "react";

export const teamStyles: Record<string, CSSProperties> = {
  "ATL" : { color: '#FDB927', backgroundColor: '#C8102E' },
  "BOS" : { color: 'white', backgroundColor: '#007A33'},
  "BKN" : { color: 'white', backgroundColor: 'black'},
  "CHA" : { color: 'white', backgroundColor: '#00788C' },
  "CHI" : { color: 'white', backgroundColor: '#CE1141' },
  "CLE" : { color: '#FDBB30', backgroundColor: '#860038'},
  "DAL" : { color: 'white', backgroundColor: '#002B5E'},
  "DEN" : { color: '#fec524', backgroundColor: '#0e2240' },
  "DET" : { color: '#C8102E', backgroundColor: '#002D62'},
  "GSW" : { color: '#ffc72c', backgroundColor: '#1d428a' },
  "HOU" : { color: '#CE1141', backgroundColor: 'black'},
  "IND" : { color: '#002D62', backgroundColor: '#FDBB30'},
  "LAC" : { color: '#C8102E', backgroundColor: '#1D428A'},
  "LAL" : { color: '#552583', backgroundColor: '#FDB927'},
  "MEM" : { color: '#5D76A9', backgroundColor: '#12173F'},
  "MIA" : { color: ' white', backgroundColor: '#98002E'},
  "MIL" : { color: ' #EEE1C6', backgroundColor: '#00471B'},
  "MIN" : { color: '#78BE20', backgroundColor: '#0C2340'},
  "NOP" : { color: '#85714D', backgroundColor: '#0C2340'},
  "NYK" : { color: '#F58426', backgroundColor: '#006BB6'},
  "OKC" : { color: 'white', backgroundColor: '#2c4bf6' },  
  "ORL" : { color: 'black', backgroundColor: '#0077C0' },  
  "PHI" : { color: '#ED174C', backgroundColor: '#002B5C' },
  "PHX" : { color: '#E56020', backgroundColor: '#1D1160' },
  "POR" : { color: 'black', backgroundColor: '#E03A3E' },
  "SAC" : { color: 'white', backgroundColor: '#5A2D81' },
  "SAS" : { color: 'white', backgroundColor: 'black' },
  "TOR" : { color: 'black', backgroundColor: '#CE1141' },
  "UTA" : { color: '#F9A01B', backgroundColor: '#002B5C' },
  "WAS" : { color: 'white', backgroundColor: '#E31837' },
}